BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[bookmarks] ALTER COLUMN [created_at] DATETIME2 NULL;
ALTER TABLE [dbo].[bookmarks] ALTER COLUMN [updated_at] DATETIME2 NULL;
ALTER TABLE [dbo].[bookmarks] ADD CONSTRAINT [bookmarks_created_at_df] DEFAULT CURRENT_TIMESTAMP FOR [created_at];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
